spring:
  datasource:
    url: jdbc:sqlserver://abhayserver.database.windows.net:1433;database=food;user=abhay321@abhayserver;password=Abhay@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    
    username: abhay321
    password: Abhay@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      